## Which product category has the highest total stock quantity across all products?
Stock_Quantity_And_Category = 
VAR MaxStock = MAX('Inventory Management'[Stock_Quantity]) # визначаємо змінну MaxStock, яка містить максимальну кількість товарів (Stock_Quantity) у таблиці 'Inventory Management'
VAR CategoryName = CALCULATE(
    FIRSTNONBLANK('Inventory Management'[Category], 1), # функція, яка повертає перше непусте значення стовпця Category з таблиці 'Inventory Management'. Вона потрібна для того, щоб отримати категорію, яка має максимальний товар (за умови, що ці значення не порожні).
    'Inventory Management'[Stock_Quantity] = MaxStock # фільтр, який гарантує, що ми обираємо тільки той продукт (або продукти), де кількість товару (Stock_Quantity) дорівнює максимальному значенню MaxStock, яке ми знайшли на першому кроці.
)
RETURN
    ##"The highest total stock quantity: " & MaxStock & " | Category:  " & CategoryName
        "The highest total stock quantity: " & CategoryName


## How many products currently have stock quantities below their reorder point?
  Measure_Below_Reorder_Point = 
CALCULATE(
    COUNT('Inventory Management'[Diff between stock and reorder point]),
    'Inventory Management'[Stock_Quantity] < 'Inventory Management'[Reorder_Point] #повертаємо рядок, який складається з повідомлення "The highest total stock quantity: " та назви категорії (CategoryName), яку ви отримали на попередньому кроці.
)

  
## What minimum order quantity is required for a company to restock all products below the reorder point?
  Total_Order_Quantity = 
SUM('Inventory Management'[Diff between stock and reorder point]) # сума різниці між фактичним запасом і точкою перерохподілу


## Which supplier has the highest average lead time for restocking?
Avg_lead_time_suppliers = 
VAR MaxLeadTime = MAX('Suppliers lead time'[Avg_lead_time_days])
    -- Тут ми визначаємо змінну MaxLeadTime, яка знаходить максимальне значення серед середнього часу поставки (Avg_lead_time_days) в таблиці 'Suppliers lead time'.
    -- Це буде максимальний час поставки серед усіх постачальників.
VAR SupplierID = CALCULATE(
    FIRSTNONBLANK('Suppliers lead time'[Supplier_ID], 1),
    'Suppliers lead time'[Avg_lead_time_days] = MaxLeadTime
)
    -- Далі ми створюємо змінну SupplierID, яка за допомогою функції CALCULATE визначає і повертає ID постачальника, у якого середній час поставки дорівнює максимальному (MaxLeadTime).
    -- FIRSTNONBLANK повертає перше непусте значення ID постачальника для цього максимального часу поставки. Ми використовуємо фільтр, щоб взяти тільки ті рядки, де час поставки дорівнює MaxLeadTime.
RETURN
    "The highest average lead time for restocking: " & SupplierID
    -- Повертаємо текстове повідомлення, яке вказує на постачальника з найбільшим середнім часом поставки для поповнення запасів.
    -- Виводиться ID постачальника, який має найвищий середній час поставки.



## What is the average time since the last restock for products marked as "Out of Stock"?
The average time since the last restock for products marked as "Out of Stock" = ABS(AVERAGE('Inventory Management'[Time since the last restock marked as "Out of stock"]))


## Identify the months when the highest number of products were restocked - are there any seasonal trends?
To identify this I extracted number of month from "Last_Restoke_Date" column and created new column. i also used here measure in viz like SUM() to calculate the sum of reorder point according to month


## Identify the top 5 most expensive products (by unit price) and their categories.
I didn't use here any measures


## Which product category has the fastest turnover based on stock quantity and lead time?
I created new separated table where I grouped the stock quantity and lead time in days according to category and then to calculate turnover i divided the total quantity by category and total lead time by category
To calculate it i used group by in power query and count avg lead_time_days and stock quantity for each category and then used the custom formula to calculate turnover - 

[Stock_Quantity]/[AVG_Lead_Time_Days]


## Which warehouse location has the highest number of products stored?
To find the answer on this question I used measures on viz like SUM()

## Which country has the most stocked items, and which top 3 counties have the highest stocked quantities by different product categories?
I didn't use here any measures
